pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building Stage.."'
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    sh 'echo "Testing Stage.."'
                }
            }
        }
    }
}
