pipeline {
    agent any

    stages {
        stage("Initial cleanup") {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building Stage.."'
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    sh 'echo "Testing Stage.."'
                }
            }
        }
        stage('Package') {
            steps {
                script {
                    sh 'echo "Packaging App Stage.."'
                }
            }
        }
        stage('Destroy') {
            steps {
                script {
                    sh 'echo "Destroy Stage.."'
                }
            }
        }
        stage('Clean up') {
            steps {
                cleanWs()
            }
        }
    }
}
